# Generated by Django 3.2.6 on 2021-08-30 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomname',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='group_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
