# Generated by Django 3.2.6 on 2021-08-31 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20210830_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
    ]
